name: Build and Release WPF App
on:
    push:
       # branches:
       #     - main #
        tags:
            - 'v*'
jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: action/checkout@v3
        
            - name: Setup .NET SDK
              uses: action/setup-dotnet@v3
              with: 
                dontet-version: '8.0.x'
            
            - name: Build and Pack WPF Application
              run: |
                dotnet resotre
                dotnet build -c Release



        